name: News Search and Download

on:
  workflow_dispatch:  

jobs:
  search-and-save:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run News Search Script
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}  
        run: |
          mkdir -p artifacts
          TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
          OUTPUT_FILE="artifacts/news_results_${TIMESTAMP}.csv"
          python scripts/news_search.py --output $OUTPUT_FILE
          echo "OUTPUT_FILE=$OUTPUT_FILE" >> $GITHUB_ENV

      - name: Upload CSV Artifact
        uses: actions/upload-artifact@v4
        with:
          name: news_results
          path: ${{ env.OUTPUT_FILE }}
